import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Zap, Brain, Target, Utensils, BarChartBig, UserCircle } from 'lucide-react';
import { motion } from 'framer-motion';

const FeatureCard = ({ icon, title, description, delay }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ delay: delay, duration: 0.5 }}
  >
    <Card className="bg-card border-border text-card-foreground h-full transform hover:scale-105 transition-transform duration-300 shadow-lg">
      <CardHeader className="flex flex-row items-center gap-4">
        {React.cloneElement(icon, { className: "w-10 h-10 text-primary" })}
        <CardTitle className="text-xl text-foreground">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <CardDescription className="text-muted-foreground">{description}</CardDescription>
      </CardContent>
    </Card>
  </motion.div>
);

const HomePage = () => {
  return (
    <div className="space-y-16 py-8">
      <motion.section 
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.7 }}
        className="text-center py-16 bg-gradient-to-br from-gray-800/50 via-background to-gray-700/50 rounded-xl shadow-2xl"
      >
        <div className="container mx-auto px-4">
          <motion.h1 
            className="text-5xl md:text-7xl font-extrabold mb-6"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <span className="gradient-text">FitSyncX</span>
          </motion.h1>
          <motion.p 
            className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-3xl mx-auto"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.5 }}
          >
            Your AI-Powered Fitness & Nutrition Companion. Achieve your health goals with personalized plans, smart tracking, and motivating rewards.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.6, duration: 0.5 }}
          >
            <Button size="lg" className="bg-primary hover:bg-primary/90 text-primary-foreground text-lg px-10 py-6 rounded-full shadow-lg transform hover:scale-105 transition-transform duration-300">
              Get Started Now <Zap className="ml-2 h-5 w-5" />
            </Button>
          </motion.div>
          <div className="mt-12">
            <img className="mx-auto rounded-lg shadow-xl w-full max-w-3xl h-auto" alt="FitSyncX app interface mockup on a device" src="https://images.unsplash.com/photo-1593150543200-56e05bdb018e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80" />
          </div>
        </div>
      </motion.section>

      <section className="container mx-auto px-4">
        <h2 className="text-4xl font-bold text-center mb-12 text-foreground">
          Why <span className="gradient-text">FitSyncX</span>?
        </h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <FeatureCard 
            icon={<Brain />} 
            title="AI-Driven Plans" 
            description="Smart calorie tracking and personalized meal plans generated by AI."
            delay={0.2}
          />
          <FeatureCard 
            icon={<Target />} 
            title="Goal Oriented" 
            description="Set your fitness goals and let FitSyncX guide you every step of the way."
            delay={0.4}
          />
          <FeatureCard 
            icon={<Utensils />} 
            title="Guided Recipes" 
            description="Delicious and healthy recipes with smart grocery lists to make cooking easy."
            delay={0.6}
          />
          <FeatureCard 
            icon={<BarChartBig />} 
            title="Progress Tracking" 
            description="Monitor your daily progress and stay motivated with insightful analytics."
            delay={0.8}
          />
          <FeatureCard 
            icon={<Zap />} 
            title="Motivation Engine" 
            description="Earn rewards for consistency and stay engaged with our unique motivation system."
            delay={1.0}
          />
           <FeatureCard 
            icon={<UserCircle />} 
            title="Community Support" 
            description="Connect with others, share your journey, and get inspired. (Coming Soon!)"
            delay={1.2}
          />
        </div>
      </section>

      <motion.section 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1, duration: 0.7 }}
        className="container mx-auto px-4 py-16 text-center glassmorphism-card"
      >
        <h2 className="text-4xl font-bold mb-6 text-foreground">Ready to Transform Your Health?</h2>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Join FitSyncX today and embark on a personalized journey to a healthier, happier you.
        </p>
        <Button size="lg" className="bg-primary hover:bg-primary/90 text-primary-foreground text-lg px-10 py-6 rounded-full shadow-lg transform hover:scale-105 transition-transform duration-300">
          Start Your Journey
        </Button>
      </motion.section>
    </div>
  );
};

export default HomePage;